/** Design tokens copied from design-reference/code.html (Stitch export) — keep in sync with DESIGN.md. */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{html,js}', './build.mjs'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#2a1700',
        'on-secondary-fixed-variant': '#00522e',
        'inverse-surface': '#e2e2e5',
        'primary-fixed-dim': '#ffb3ac',
        'surface-variant': '#333537',
        primary: '#ffb3ac',
        'on-surface': '#e2e2e5',
        'surface-container-lowest': '#0c0e10',
        'on-error-container': '#ffdad6',
        surface: '#121416',
        'on-primary-fixed-variant': '#93000f',
        outline: '#ad8884',
        'tertiary-container': '#a66900',
        'primary-fixed': '#ffdad6',
        'on-primary': '#680008',
        'surface-container-highest': '#333537',
        'on-surface-variant': '#e7bdb8',
        'on-primary-container': '#ffffff',
        'on-secondary-fixed': '#00210f',
        'surface-bright': '#38393c',
        background: '#121416',
        'inverse-on-surface': '#2f3133',
        'surface-container': '#1e2022',
        'outline-variant': '#5d3f3c',
        'error-container': '#93000a',
        'on-tertiary': '#472a00',
        'tertiary-fixed-dim': '#ffb95f',
        'surface-container-low': '#1a1c1e',
        'inverse-primary': '#c00017',
        'secondary-fixed': '#8ef8b5',
        'on-secondary': '#00391e',
        'secondary-fixed-dim': '#72db9b',
        secondary: '#72db9b',
        'on-tertiary-fixed-variant': '#653e00',
        tertiary: '#ffb95f',
        'on-error': '#690005',
        'secondary-container': '#00834c',
        'surface-dim': '#121416',
        'on-secondary-container': '#e5ffe9',
        'tertiary-fixed': '#ffddb8',
        'surface-tint': '#ffb3ac',
        'primary-container': '#e5242a',
        'on-background': '#e2e2e5',
        'surface-container-high': '#282a2c',
        error: '#ffb4ab',
        'on-primary-fixed': '#410003',
        'on-tertiary-container': '#ffffff',
      },
      borderRadius: { DEFAULT: '0.125rem', lg: '0.25rem', xl: '0.5rem', full: '0.75rem' },
      spacing: {
        'margin-mobile': '1rem',
        'gutter-mobile': '1rem',
        'space-xs': '0.25rem',
        'space-xl': '2.5rem',
        'space-2xl': '4rem',
        'space-sm': '0.5rem',
        gutter: '1.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        margin: '2rem',
      },
      fontFamily: {
        'label-lg': ['Space Grotesk', 'sans-serif'],
        'metric-gauge': ['Chivo', 'sans-serif'],
        'display-hero': ['Chivo', 'sans-serif'],
        'title-lg': ['Space Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Chivo', 'sans-serif'],
        'body-lg': ['Space Grotesk', 'sans-serif'],
        'label-sm': ['Space Grotesk', 'sans-serif'],
        'display-hero-mobile': ['Chivo', 'sans-serif'],
        'headline-md': ['Chivo', 'sans-serif'],
        'headline-lg': ['Chivo', 'sans-serif'],
        'title-md': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Space Grotesk', 'sans-serif'],
        'headline-sm': ['Chivo', 'sans-serif'],
      },
      fontSize: {
        'label-lg': ['13px', { lineHeight: '18px', fontWeight: '700' }],
        'metric-gauge': ['32px', { lineHeight: '36px', fontWeight: '900' }],
        'display-hero': ['56px', { lineHeight: '64px', fontWeight: '900' }],
        'title-lg': ['18px', { lineHeight: '24px', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '800' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '700' }],
        'display-hero-mobile': ['36px', { lineHeight: '44px', fontWeight: '900' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-lg': ['40px', { lineHeight: '48px', fontWeight: '800' }],
        'title-md': ['16px', { lineHeight: '22px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-sm': ['22px', { lineHeight: '28px', fontWeight: '700' }],
      },
    },
  },
};
